In [4]:
import pandas as pd

data = {"house-size": [1200,1300,1250,1400,1100],
        "location": ['Bombay', 'Delhi', 'chennai', 'Bombay', 'Delhi']}

print(data)
my_df=pd.DataFrame(data)

print(my_df)

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(my_df['location'].values)
x=vectorizer.transform(my_df['location'].values)
print(x)
print(vectorizer.get_feature_names_out())
print(x.toarray())

{'house-size': [1200, 1300, 1250, 1400, 1100], 'location': ['Bombay', 'Delhi', 'chennai', 'Bombay', 'Delhi']}
   house-size location
0        1200   Bombay
1        1300    Delhi
2        1250  chennai
3        1400   Bombay
4        1100    Delhi
  (np.int32(0), np.int32(0))	1
  (np.int32(1), np.int32(2))	1
  (np.int32(2), np.int32(1))	1
  (np.int32(3), np.int32(0))	1
  (np.int32(4), np.int32(2))	1
['bombay' 'chennai' 'delhi']
[[1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]]
